"""词对数据库 — 谁是卧底"""

WORD_PAIRS = [
    # 水果
    {"civilian": "苹果", "spy": "梨"},
    {"civilian": "西瓜", "spy": "哈密瓜"},
    {"civilian": "香蕉", "spy": "芭蕉"},
    {"civilian": "橘子", "spy": "橙子"},
    {"civilian": "葡萄", "spy": "提子"},
    {"civilian": "草莓", "spy": "树莓"},
    {"civilian": "桃子", "spy": "杏子"},
    {"civilian": "樱桃", "spy": "车厘子"},
    # 饮品
    {"civilian": "牛奶", "spy": "豆浆"},
    {"civilian": "咖啡", "spy": "奶茶"},
    {"civilian": "可乐", "spy": "雪碧"},
    {"civilian": "啤酒", "spy": "香槟"},
    {"civilian": "绿茶", "spy": "抹茶"},
    # 动物
    {"civilian": "猫", "spy": "老虎"},
    {"civilian": "狗", "spy": "狼"},
    {"civilian": "马", "spy": "驴"},
    {"civilian": "海豚", "spy": "鲨鱼"},
    {"civilian": "兔子", "spy": "仓鼠"},
    {"civilian": "鸽子", "spy": "海鸥"},
    {"civilian": "蝴蝶", "spy": "蛾子"},
    {"civilian": "青蛙", "spy": "蟾蜍"},
    # 交通
    {"civilian": "火车", "spy": "地铁"},
    {"civilian": "公交车", "spy": "大巴"},
    {"civilian": "自行车", "spy": "电动车"},
    {"civilian": "轮船", "spy": "游艇"},
    {"civilian": "直升机", "spy": "无人机"},
    {"civilian": "出租车", "spy": "网约车"},
    # 职业
    {"civilian": "医生", "spy": "护士"},
    {"civilian": "老师", "spy": "教授"},
    {"civilian": "警察", "spy": "保安"},
    {"civilian": "厨师", "spy": "烘焙师"},
    {"civilian": "歌手", "spy": "演员"},
    {"civilian": "作家", "spy": "编辑"},
    {"civilian": "律师", "spy": "法官"},
    # 运动
    {"civilian": "篮球", "spy": "排球"},
    {"civilian": "足球", "spy": "橄榄球"},
    {"civilian": "羽毛球", "spy": "网球"},
    {"civilian": "游泳", "spy": "潜水"},
    {"civilian": "跑步", "spy": "竞走"},
    {"civilian": "拳击", "spy": "跆拳道"},
    # 乐器
    {"civilian": "钢琴", "spy": "小提琴"},
    {"civilian": "吉他", "spy": "尤克里里"},
    {"civilian": "笛子", "spy": "箫"},
    {"civilian": "二胡", "spy": "马头琴"},
    # 家具
    {"civilian": "沙发", "spy": "椅子"},
    {"civilian": "桌子", "spy": "茶几"},
    {"civilian": "床", "spy": "榻榻米"},
    {"civilian": "衣柜", "spy": "书柜"},
    {"civilian": "台灯", "spy": "落地灯"},
    # 电子产品
    {"civilian": "手机", "spy": "平板电脑"},
    {"civilian": "笔记本电脑", "spy": "台式电脑"},
    {"civilian": "电视", "spy": "投影仪"},
    {"civilian": "耳机", "spy": "音响"},
    {"civilian": "相机", "spy": "摄像机"},
    {"civilian": "手表", "spy": "手环"},
    # 日常用品
    {"civilian": "雨伞", "spy": "遮阳伞"},
    {"civilian": "眼镜", "spy": "墨镜"},
    {"civilian": "口红", "spy": "唇膏"},
    {"civilian": "香水", "spy": "花露水"},
    {"civilian": "毛巾", "spy": "浴巾"},
    {"civilian": "枕头", "spy": "抱枕"},
    {"civilian": "牙刷", "spy": "电动牙刷"},
    {"civilian": "拖鞋", "spy": "凉鞋"},
    # 食物
    {"civilian": "面条", "spy": "米线"},
    {"civilian": "饺子", "spy": "馄饨"},
    {"civilian": "蛋糕", "spy": "面包"},
    {"civilian": "火锅", "spy": "麻辣烫"},
    {"civilian": "披萨", "spy": "馅饼"},
    {"civilian": "寿司", "spy": "饭团"},
    {"civilian": "薯片", "spy": "薯条"},
    {"civilian": "冰淇淋", "spy": "雪糕"},
    {"civilian": "汉堡", "spy": "三明治"},
    # 植物
    {"civilian": "玫瑰", "spy": "月季"},
    {"civilian": "竹子", "spy": "甘蔗"},
    {"civilian": "仙人掌", "spy": "芦荟"},
    {"civilian": "向日葵", "spy": "菊花"},
    {"civilian": "松树", "spy": "柏树"},
    {"civilian": "荷花", "spy": "睡莲"},
    # 家用电器
    {"civilian": "空调", "spy": "风扇"},
    {"civilian": "洗衣机", "spy": "洗碗机"},
    {"civilian": "冰箱", "spy": "冰柜"},
    {"civilian": "微波炉", "spy": "烤箱"},
    {"civilian": "吸尘器", "spy": "扫地机器人"},
    # 建筑 / 场所
    {"civilian": "电梯", "spy": "扶梯"},
    {"civilian": "医院", "spy": "诊所"},
    {"civilian": "图书馆", "spy": "书店"},
    {"civilian": "健身房", "spy": "体育馆"},
    {"civilian": "超市", "spy": "便利店"},
    {"civilian": "酒店", "spy": "民宿"},
    # 服饰
    {"civilian": "衬衫", "spy": "T恤"},
    {"civilian": "羽绒服", "spy": "棉袄"},
    {"civilian": "运动鞋", "spy": "跑鞋"},
    {"civilian": "围巾", "spy": "披肩"},
    {"civilian": "帽子", "spy": "头盔"},
    # 文具
    {"civilian": "铅笔", "spy": "自动铅笔"},
    {"civilian": "橡皮", "spy": "修正带"},
    {"civilian": "笔记本", "spy": "日记本"},
    {"civilian": "书包", "spy": "双肩包"},
]
